language: c++

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8.5
      env:
         - MATRIX_EVAL="CC=gcc-4.8.5 && CXX=g++-4.8.5"
env:
  global:
    - secure: ${GITHUB_TOKEN}
  matrix:
    - TRAVIS_EMPTY_JOB_WORKAROUND=true

script: make main
