# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_sodium', [dirname(__file__)])
        except ImportError:
            import _sodium
            return _sodium
        if fp is not None:
            try:
                _mod = imp.load_module('_sodium', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _sodium = swig_import_helper()
    del swig_import_helper
else:
    import _sodium
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


FATAL = _sodium.FATAL
WARN = _sodium.WARN
ERROR = _sodium.ERROR
DEBUG = _sodium.DEBUG
TRACE = _sodium.TRACE
INFO = _sodium.INFO
class Logwriter(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Logwriter, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Logwriter, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _sodium.new_Logwriter(*args)
        try: self.this.append(this)
        except: self.this = this
    def write(self, *args): return _sodium.Logwriter_write(self, *args)
    def getTime(self): return _sodium.Logwriter_getTime(self)
    __swig_destroy__ = _sodium.delete_Logwriter
    __del__ = lambda self : None;
Logwriter_swigregister = _sodium.Logwriter_swigregister
Logwriter_swigregister(Logwriter)

class InitParser(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, InitParser, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, InitParser, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _sodium.new_InitParser(*args)
        try: self.this.append(this)
        except: self.this = this
    def findLine(self): return _sodium.InitParser_findLine(self)
    def readLine(self): return _sodium.InitParser_readLine(self)
    __swig_setmethods__["iniContainer"] = _sodium.InitParser_iniContainer_set
    __swig_getmethods__["iniContainer"] = _sodium.InitParser_iniContainer_get
    if _newclass:iniContainer = _swig_property(_sodium.InitParser_iniContainer_get, _sodium.InitParser_iniContainer_set)
    __swig_destroy__ = _sodium.delete_InitParser
    __del__ = lambda self : None;
InitParser_swigregister = _sodium.InitParser_swigregister
InitParser_swigregister(InitParser)

class TimeCounter(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TimeCounter, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TimeCounter, name)
    __repr__ = _swig_repr
    def timeStart(self): return _sodium.TimeCounter_timeStart(self)
    def zawarudo(self): return _sodium.TimeCounter_zawarudo(self)
    __swig_setmethods__["start"] = _sodium.TimeCounter_start_set
    __swig_getmethods__["start"] = _sodium.TimeCounter_start_get
    if _newclass:start = _swig_property(_sodium.TimeCounter_start_get, _sodium.TimeCounter_start_set)
    __swig_setmethods__["end"] = _sodium.TimeCounter_end_set
    __swig_getmethods__["end"] = _sodium.TimeCounter_end_get
    if _newclass:end = _swig_property(_sodium.TimeCounter_end_get, _sodium.TimeCounter_end_set)
    def __init__(self): 
        this = _sodium.new_TimeCounter()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _sodium.delete_TimeCounter
    __del__ = lambda self : None;
TimeCounter_swigregister = _sodium.TimeCounter_swigregister
TimeCounter_swigregister(TimeCounter)

# This file is compatible with both classic and new-style classes.


